services:
  web:
    image: scrum-estimation-web:latest
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_WEBSOCKET_API_URL=${NEXT_PUBLIC_WEBSOCKET_API_URL}
    environment:
      - REDIS_URL=${REDIS_URL}
      - SESSION_TOKEN=${SESSION_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - websockets
    restart: unless-stopped

  websockets:
    image: scrum-estimation-websockets:latest
    build:
      context: .
      dockerfile: apps/websockets/Dockerfile
    environment:
      - WEBSCOKET_CORS_ORIGIN=${WEBSCOKET_CORS_ORIGIN}
      - SERVER_PORT=${SERVER_PORT}
      - REDIS_URL=${REDIS_URL}
      - SESSION_TOKEN=${SESSION_TOKEN}
    ports:
      - "3001:3001"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "3002:6379"
    restart: unless-stopped
