services:
  web:
    image: scrum-estimation-web:latest
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_WEBSOCKET_API_URL=http://localhost:3001
    environment:
      - REDIS_URL=redis://redis:6379
      - SESSION_TOKEN=changeAndHideMeM8WithARealEnvironmentVariable
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - websockets
    restart: unless-stopped

  websockets:
    image: scrum-estimation-websockets:latest
    build:
      context: .
      dockerfile: apps/websockets/Dockerfile
    environment:
      - WEBSCOKET_CORS_ORIGIN=http://localhost:3000
      - SERVER_PORT=3001
      - REDIS_URL=redis://redis:6379
      - SESSION_TOKEN=changeAndHideMeM8WithARealEnvironmentVariable
    ports:
      - "3001:3001"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
